version: '3'

services:
  registan:
    image: qahhor/registan
    container_name: "registan"
    restart: always
    ports:
      - "80:5000"
    networks:
      - web

networks:
  web:
    external: true